[package]
name = "rsproxy"
version = "0.1.3"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
tracing-subscriber = { version = "0.2.5", default-features = false, features = ["env-filter", "fmt", "ansi", "chrono"]}
clap = { version = "3.0.7", features = ["derive"] }
tokio = { version = "1.16", features = ["full"] }
pretty_env_logger = "0.4.0"
log = "0.4.14"
chrono = "0.4.19"
anyhow = "1.0.44"
tracing = "0.1.29"
futures-util = "0.3.17"
pin-utils = "0.1.0"
byte-pool = "0.2.3"
num_cpus = "1.13.1"
url = "2.2.2"
regex = "1.5"
notify = "4.0"

[target.aarch64-linux-android.dependencies]
jni = "0.19"
android_logger = "0.10"





######### build shared lib for android ###########
# cargo build --target=aarch64-linux-android --release --lib
